[app]
ns="KakaoAuthDemo"
stage="Dev"

[aws]
region="ap-northeast-2"

[auth]
# https://developers.kakao.com/
clientId="" # Kakaotalk application rest api key
clientSecret="" # Kakaotalk application secret key
scopes=["openid"] # Kakao OIDC scopes does not support "email" scope
redirectUris=["http://localhost:3000/callback"]