[app]
ns="KakaoAuthDemo"
stage="Dev"

[aws]
region="ap-northeast-2"

[auth]
clientId="your_client_id"
clientSecret="your_client_secret"
scopes=["openid"]
redirectUris=["http://localhost:3000/auth/callback"]