[app]
ns="KakaoAuthDemo"
stage="Dev"

[aws]
region="ap-northeast-2"

[auth]
clientId="kakaotalk application rest api key"
clientSecret="kakaotalk application secret key"
scopes=["openid"]
redirectUris=["http://localhost:3000/callback"]